dist: trusty
sudo: required
language: node_js

cache:
  yarn: true

addons:
  chrome: stable

matrix:
  include:
    - os: linux
      node_js: "8"
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
    - os: osx
      node_js: "8"
    - os: osx
      node_js: "9"
    - os: osx
      node_js: "10"
  fast_finish: true

install: yarn install
script: yarn test
