dist: trusty
sudo: required
language: node_js

cache:
  yarn: true

addons:
  chrome: stable

matrix:
  include:
    - os: linux
      node_js: "8"
      before_script:
        - xvfb-run make test
    - os: osx
      node_js: "8"
  fast_finish: true

install: yarn install
script: yarn test
