sudo: false
dist: trusty
language: node_js

cache:
  yarn: true

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: osx
      node_js: "8"
  fast_finish: true

install: yarn install
script: yarn test
