dist: trusty
sudo: required
language: node_js

cache:
  yarn: true

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

matrix:
  include:
    - os: linux
      node_js: "8"
    - os: osx
      node_js: "8"
  fast_finish: true

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
install: yarn install
script: yarn test
